openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/banners:
    get:
      summary: ''
      operationId: getApiBanners
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 6
                      image: 'http://localhost/storage/vitae'
                    -
                      id: 7
                      image: 'http://localhost/storage/reiciendis'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 6
                        image: 'http://localhost/storage/vitae'
                      -
                        id: 7
                        image: 'http://localhost/storage/reiciendis'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 6
                        image:
                          type: string
                          example: 'http://localhost/storage/vitae'
      tags:
        - Banner
      security: []
  /api/brands:
    get:
      summary: ''
      operationId: getApiBrands
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 11
                      image: impedit
                      name: 'Prof. Raul Konopelski V'
                      address: 'Numquam non explicabo laudantium vero. Neque cumque mollitia non sint. Cupiditate ipsum omnis ea aut. Vero qui ut necessitatibus non recusandae perferendis.'
                      telephone: facilis
                      phone: '(917) 485-9690'
                      description: 'Ut amet consequuntur praesentium illum similique et. Dolores temporibus ut ratione dolor maiores. Mollitia temporibus reprehenderit qui rerum ut voluptatum libero.'
                      categories: []
                      products: []
                    -
                      id: 12
                      image: aliquam
                      name: 'Ms. Alisha Morar Sr.'
                      address: 'Consequuntur quis neque nobis et et. Repellat ad nihil est reprehenderit. Dolorem sed officiis et dolores eveniet. Dolores reiciendis ratione eos laudantium.'
                      telephone: quisquam
                      phone: '(863) 599-3531'
                      description: 'Laboriosam commodi assumenda voluptas perferendis magni dolor asperiores ut. Officia animi ducimus atque quia reprehenderit. Nesciunt non vitae laboriosam ab.'
                      categories: []
                      products: []
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 11
                        image: impedit
                        name: 'Prof. Raul Konopelski V'
                        address: 'Numquam non explicabo laudantium vero. Neque cumque mollitia non sint. Cupiditate ipsum omnis ea aut. Vero qui ut necessitatibus non recusandae perferendis.'
                        telephone: facilis
                        phone: '(917) 485-9690'
                        description: 'Ut amet consequuntur praesentium illum similique et. Dolores temporibus ut ratione dolor maiores. Mollitia temporibus reprehenderit qui rerum ut voluptatum libero.'
                        categories: []
                        products: []
                      -
                        id: 12
                        image: aliquam
                        name: 'Ms. Alisha Morar Sr.'
                        address: 'Consequuntur quis neque nobis et et. Repellat ad nihil est reprehenderit. Dolorem sed officiis et dolores eveniet. Dolores reiciendis ratione eos laudantium.'
                        telephone: quisquam
                        phone: '(863) 599-3531'
                        description: 'Laboriosam commodi assumenda voluptas perferendis magni dolor asperiores ut. Officia animi ducimus atque quia reprehenderit. Nesciunt non vitae laboriosam ab.'
                        categories: []
                        products: []
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 11
                        image:
                          type: string
                          example: impedit
                        name:
                          type: string
                          example: 'Prof. Raul Konopelski V'
                        address:
                          type: string
                          example: 'Numquam non explicabo laudantium vero. Neque cumque mollitia non sint. Cupiditate ipsum omnis ea aut. Vero qui ut necessitatibus non recusandae perferendis.'
                        telephone:
                          type: string
                          example: facilis
                        phone:
                          type: string
                          example: '(917) 485-9690'
                        description:
                          type: string
                          example: 'Ut amet consequuntur praesentium illum similique et. Dolores temporibus ut ratione dolor maiores. Mollitia temporibus reprehenderit qui rerum ut voluptatum libero.'
                        categories:
                          type: array
                          example: []
                        products:
                          type: array
                          example: []
      tags:
        - Brand
      security: []
  /api/carts:
    get:
      summary: ''
      operationId: getApiCarts
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data: []
                properties:
                  data:
                    type: array
                    example: []
      tags:
        - Cart
      security: []
    post:
      summary: ''
      operationId: postApiCarts
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: ''
                  example: 18
                product_id:
                  type: integer
                  description: ''
                  example: 14
                quantity:
                  type: number
                  description: ''
                  example: 1323435.543346
              required:
                - user_id
                - product_id
                - quantity
      security: []
  '/api/carts/{id}':
    put:
      summary: ''
      operationId: putApiCartsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: ''
                  example: 12
                product_id:
                  type: integer
                  description: ''
                  example: 2
                quantity:
                  type: number
                  description: ''
                  example: 497.0411474
              required:
                - user_id
                - product_id
                - quantity
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the cart.'
        example: 8
        required: true
        schema:
          type: integer
  /api/categories:
    get:
      summary: ''
      operationId: getApiCategories
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 6
                      name: 'Prof. Marina Gleason PhD'
                    -
                      id: 7
                      name: 'Dr. Jordan Kertzmann Jr.'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 6
                        name: 'Prof. Marina Gleason PhD'
                      -
                        id: 7
                        name: 'Dr. Jordan Kertzmann Jr.'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 6
                        name:
                          type: string
                          example: 'Prof. Marina Gleason PhD'
      tags:
        - Category
      security: []
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/orders:
    get:
      summary: ''
      operationId: getApiOrders
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      user_id: 7
                    -
                      id: 2
                      user_id: 8
                    -
                      id: 3
                      user_id: 9
                    -
                      id: 4
                      user_id: 10
                    -
                      id: 5
                      user_id: 11
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        user_id: 7
                      -
                        id: 2
                        user_id: 8
                      -
                        id: 3
                        user_id: 9
                      -
                        id: 4
                        user_id: 10
                      -
                        id: 5
                        user_id: 11
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        user_id:
                          type: integer
                          example: 7
      tags:
        - Order
      security: []
    post:
      summary: ''
      operationId: postApiOrders
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: ''
                  example: 15
              required:
                - user_id
      security: []
  /api/products:
    get:
      summary: ''
      operationId: getApiProducts
      description: ''
      parameters:
        -
          in: query
          name: search
          description: 'the text that you want to search for'
          example: test
          required: false
          schema:
            type: string
            description: 'the text that you want to search for'
            example: test
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 6
                      name: 'Brad Altenwerth'
                      description: 'Delectus earum assumenda similique in. Dolorem assumenda harum dolorem hic reprehenderit et. Dicta inventore et possimus eius. Qui reiciendis itaque natus autem labore sed.'
                      image: quo
                      regular_price: 7733513860
                      sale_price: 5777305427
                      on_sale: true
                      discount_percentage: 19562084.33
                    -
                      id: 7
                      name: 'Cara Hoeger'
                      description: 'In error omnis ex. Et blanditiis neque vero harum eos amet ad. Labore incidunt aliquid ipsam debitis labore.'
                      image: doloribus
                      regular_price: 6422737723
                      sale_price: 4030808361
                      on_sale: true
                      discount_percentage: 23919293.62
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 6
                        name: 'Brad Altenwerth'
                        description: 'Delectus earum assumenda similique in. Dolorem assumenda harum dolorem hic reprehenderit et. Dicta inventore et possimus eius. Qui reiciendis itaque natus autem labore sed.'
                        image: quo
                        regular_price: 7733513860
                        sale_price: 5777305427
                        on_sale: true
                        discount_percentage: 19562084.33
                      -
                        id: 7
                        name: 'Cara Hoeger'
                        description: 'In error omnis ex. Et blanditiis neque vero harum eos amet ad. Labore incidunt aliquid ipsam debitis labore.'
                        image: doloribus
                        regular_price: 6422737723
                        sale_price: 4030808361
                        on_sale: true
                        discount_percentage: 23919293.62
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 6
                        name:
                          type: string
                          example: 'Brad Altenwerth'
                        description:
                          type: string
                          example: 'Delectus earum assumenda similique in. Dolorem assumenda harum dolorem hic reprehenderit et. Dicta inventore et possimus eius. Qui reiciendis itaque natus autem labore sed.'
                        image:
                          type: string
                          example: quo
                        regular_price:
                          type: integer
                          example: 7733513860
                        sale_price:
                          type: integer
                          example: 5777305427
                        on_sale:
                          type: boolean
                          example: true
                        discount_percentage:
                          type: number
                          example: 19562084.33
      tags:
        - Product
      security: []
  '/api/products/{id}':
    get:
      summary: ''
      operationId: getApiProductsId
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 6
                    name: 'Alford Simonis'
                    description: 'Ipsam nesciunt est et consectetur sunt molestias. Minus dolores distinctio necessitatibus culpa maiores dolores.'
                    image: distinctio
                    regular_price: 8910740962
                    sale_price: 9856337000
                    on_sale: true
                    discount_percentage: -9455960.38
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 6
                      name:
                        type: string
                        example: 'Alford Simonis'
                      description:
                        type: string
                        example: 'Ipsam nesciunt est et consectetur sunt molestias. Minus dolores distinctio necessitatibus culpa maiores dolores.'
                      image:
                        type: string
                        example: distinctio
                      regular_price:
                        type: integer
                        example: 8910740962
                      sale_price:
                        type: integer
                        example: 9856337000
                      on_sale:
                        type: boolean
                        example: true
                      discount_percentage:
                        type: number
                        example: -9455960.38
      tags:
        - Product
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Banner
    description: ''
  -
    name: Brand
    description: ''
  -
    name: Cart
    description: ''
  -
    name: Category
    description: ''
  -
    name: Endpoints
    description: ''
  -
    name: Order
    description: ''
  -
    name: Product
    description: ''
